services:
  db:
    image: mysql:8.0
    command: --log-bin-trust-function-creators=1
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: kK#47jLp56
      MYSQL_DATABASE: paladins_db
      MYSQL_USER: djangoApp
      MYSQL_PASSWORD: Kk#47JlP56m@c@
    ports:
      - "3306:3306"

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:9000 gerenciador_de_vendas.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:9000"
    depends_on:
      - db
    environment:
      DB_NAME: paladins_db
      DB_USER: djangoApp
      DB_PASSWORD: Kk#47JlP56m@c@
      DB_HOST: db
      DB_PORT: 3306
      GERENTE_PASSWORD: password
      FUNCIONARIO_PASSWORD: password
      SUPERUSER_PASSWORD: password123

volumes:
  mysql_data:

